# Generated by Django 4.2.3 on 2023-08-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sozler", "0003_yorumsozler_favorisozler_begenisozler"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sozler",
            name="Model",
            field=models.CharField(
                choices=[
                    ("Şiirler", "Şiirler"),
                    ("Şairler", "Şairler"),
                    ("Sözler", "Sözler"),
                    ("Hikayeler", "Hikayeler"),
                    ("EnglishSiir", "EnglishSiir"),
                ],
                help_text="Modele göre sılanma ve konumlandırılma olacaktır.",
                max_length=20,
            ),
        ),
    ]
