# Generated by Django 4.2.3 on 2023-08-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sozler", "0005_sozler_usermi"),
    ]

    operations = [
        migrations.AddField(
            model_name="sozler",
            name="aciklama",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
