# Generated by Django 4.2.3 on 2023-08-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userPanel", "0002_alter_customuser_options_customuser_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="customuser", options={},),
        migrations.RemoveField(model_name="customuser", name="date_joined",),
        migrations.RemoveField(model_name="customuser", name="groups",),
        migrations.RemoveField(model_name="customuser", name="is_superuser",),
        migrations.RemoveField(model_name="customuser", name="user_permissions",),
    ]
