# Generated by Django 4.2.3 on 2023-08-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userPanel", "0003_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
