# Generated by Django 4.2.3 on 2023-08-12 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userPanel", "0005_customuser_kapak_resmi"),
    ]

    operations = [
        migrations.CreateModel(
            name="YorumSairUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icerik", models.TextField()),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "sairUser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yorumlarSairUser",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "yazar",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="yorumlarSairYazar",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FavoriSairUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorisairuser_kullanici",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sairUser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorisairuser_sairuser",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BegeniSairUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="begenisairuser_kullanici",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sairUser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="begenisairuser_sairuser",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
