# Generated by Django 4.2.3 on 2023-08-05 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hikayeler", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hikayeler",
            name="Model",
            field=models.CharField(
                choices=[
                    ("Şiirler", "Şiirler"),
                    ("Şairler", "Şairler"),
                    ("Sözler", "Sözler"),
                    ("Hikayeler", "Hikayeler"),
                    ("EnglishSiir", "EnglishSiir"),
                ],
                help_text="Modele göre sılanma ve konumlandırılma olacaktır.",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="YorumHikayeler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icerik", models.TextField()),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "hikayeler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yorumlar",
                        to="hikayeler.hikayeler",
                    ),
                ),
                (
                    "yazar",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FavoriHikayeler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "hikayeler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hikayeler.hikayeler",
                    ),
                ),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BegeniHikayeler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "hikayeler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hikayeler.hikayeler",
                    ),
                ),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
