# Generated by Django 4.2.3 on 2023-08-05 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "hikayeler",
            "0002_alter_hikayeler_model_yorumhikayeler_favorihikayeler_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="hikayeler",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Hikayeyi URL'de görünecek kısmını girin.",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="hikayeler",
            name="title",
            field=models.CharField(
                help_text="Hikayenin başlığını girin.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="hikayeler",
            name="yazar",
            field=models.ForeignKey(
                help_text="Hikayeyi yazan kullanıcıyı seçin.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
