# Generated by Django 4.2.3 on 2023-08-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hikayeler", "0003_alter_hikayeler_slug_alter_hikayeler_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hikayeler",
            name="usermi",
            field=models.BooleanField(default=False),
        ),
    ]
