# Generated by Django 4.2.3 on 2023-08-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hikayeler", "0004_hikayeler_usermi"),
    ]

    operations = [
        migrations.RemoveField(model_name="hikayeler", name="kapak_resmi",),
    ]
