# Generated by Django 4.2.3 on 2023-08-03 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("siirler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siirler",
            name="aciklama",
            field=models.CharField(
                blank=True,
                help_text="Kullanıcının işlem durumunu gösterir.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Yorum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icerik", models.TextField()),
                ("olusturma_tarihi", models.DateTimeField(auto_now_add=True)),
                (
                    "siir",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yorumlar",
                        to="siirler.siirler",
                    ),
                ),
                (
                    "yazar",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Favori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "siir",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="siirler.siirler",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Begeni",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kullanici",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "siir",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="siirler.siirler",
                    ),
                ),
            ],
        ),
    ]
