# Generated by Django 4.2.3 on 2023-08-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siirler", "0003_begeni_olusturma_tarihi_favori_olusturma_tarihi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siirler",
            name="okunma_sayisi",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="siirler",
            name="status",
            field=models.CharField(
                choices=[
                    ("Taslak", "Taslak"),
                    ("Hazir", "Hazir"),
                    ("Yayinda", "Yayinda"),
                    ("Kontrol", "Kontrol"),
                    ("Reddedildi", "Reddedildi"),
                ],
                default="Taslak",
                help_text="Şiirin durumunu seçin.",
                max_length=10,
            ),
        ),
    ]
