# Generated by Django 4.2.3 on 2023-08-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siirler", "0004_alter_siirler_okunma_sayisi_alter_siirler_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siirler",
            name="Model",
            field=models.CharField(
                choices=[
                    ("Şiirler", "Şiirler"),
                    ("Şairler", "Şairler"),
                    ("Sözler", "Sözler"),
                    ("Hikayeler", "Hikayeler"),
                    ("EnglishSiir", "EnglishSiir"),
                ],
                help_text="Modele göre sılanma ve konumlandırılma olacaktır.",
                max_length=20,
            ),
        ),
    ]
