# Generated by Django 4.2.3 on 2023-08-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siirler", "0005_alter_siirler_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="siirler",
            name="usermi",
            field=models.BooleanField(default=False),
        ),
    ]
