# Generated by Django 4.2.3 on 2023-08-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siirler", "0006_siirler_usermi"),
    ]

    operations = [
        migrations.RemoveField(model_name="siirler", name="kapak_resmi",),
        migrations.AlterField(
            model_name="siirler",
            name="aktif",
            field=models.BooleanField(
                default=False, help_text="Şiirin aktif olup olmadığını belirtin."
            ),
        ),
    ]
