# Generated by Django 4.2.3 on 2023-08-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sairler", "0004_yorumsair_favorisair_begenisair"),
    ]

    operations = [
        migrations.AddField(
            model_name="sairler",
            name="usermi",
            field=models.BooleanField(default=False),
        ),
    ]
